---
- name: Backup WazuhX Configuration
  hosts: wazuh_manager
  become: yes
  tasks:
    - name: Create backup directory
      file:
        path: /var/backups/wazuhx
        state: directory

    - name: Archive Wazuh configuration
      archive:
        path:
          - /var/ossec/etc
          - /var/ossec/ruleset
          - /var/ossec/logs
        dest: "/var/backups/wazuhx/wazuhx_backup_{{ ansible_date_time.date }}.tar.gz"
        format: gz
